# Generated by Django 4.2.7 on 2023-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_follower_created_at_remove_tweet_likes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_likes', to='main.userprofile'),
        ),
    ]
