# Generated by Django 4.2.7 on 2023-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
